import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Footer } from './footer'
import './globals.css'
import { Header } from './header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="max-w-8xl mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  )
}
